# General settings
name: 'qm9nmr-augment'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'disabled'             # online | offline | disabled
gpus: 1                     # Multi-gpu is not implemented on this branch
strategy: "ddp_find_unused_parameters_true"  # "ddp" | "ddp_find_unused_parameters_false" | null
resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null         # Use absolute path
#test_only: /home/hcchen/Di-GT-NMR-0802/outputs/2024-08-04/23-45-57-Di-GT-NMR/checkpoints/Di-GT-NMR/last-v1.ckpt

check_val_every_n_epochs: 2
val_check_interval: null
chains_to_save: 50
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif

evaluate_all_checkpoints: False
