# @package _global_
prediction_input:
  molecular_formula: 'C13H15NO3' # single molecular run
  C_H_NMR_shifts_and_HSQC: [[197.3], [110.0, 5.5], [142.0, 8.17], [48.4, 4.76, 4.76], [135.4], [127.31, 7.2], [129.01, 7.2], [126.6, 7.2], [129.02, 7.2], [127.32, 7.2], [154.6], [54.6, 3.84, 3.84, 3.84], [27.7, 2.13, 2.13, 2.13]]
  HH_COSY: [[110.0, 142.0], [127.31, 129.01], [129.01, 126.6], [126.6, 129.02], [129.02, 127.32]]
  num_OH: 0
  num_NH2: 0
  num_NH: 0
  #multi_molecules_input_files: 'inputs/example_input.csv' # Path to the batched molecular input file
                                                          # if not None, will overwrite the single molecular input
  multi_molecules_input_files: None
dataset:
  name: 'pcqm4mv2nmr-advanced-prediction-pa20-1-exp'
  edge_types: [8.4975e-01, 9.7150e-02, 8.6272e-03, 8.9793e-04, 4.2763e-02, 8.0763e-04]
train:
  batch_size: 256
  infer_start_id: 0
  multi_infer: 256
  visualize_chain: False
general:
  name: 'pcqm4mv2nmr-advanced-prediction-pa20-1-exp'
  gpus: [1]
  test_only: /home/hcchen/Di-GT-NMR-0317/src/Pretrained/pcqm4mv2nmr-advanced-best/checkpoints/pcqm4mv2nmr-advanced/epoch=1173.ckpt
  chains_to_save: 50
  log_every_steps: 1
  number_chain_steps: 50
model: # NOT NEED TO CHANGE
  type: 'discrete'
  transition: 'marginal'
  model: Di-GT-NMR
  diffusion_steps: 500
  diffusion_noise_schedule: custom
  n_layers: 20
  extra_features: all
  hidden_mlp_dims:
    X: 1024
    E: 512
    y: 512
  hidden_dims:
    dx: 1024
    de: 256
    dy: 256
    n_head: 32
    dim_ffX: 1024
    dim_ffE: 512
    dim_ffy: 512
  lambda_train:
  - 5
  - 0