# @package _global_
prediction_input:
  molecular_formula: 'C19H31NO6' # single molecular run
  C_H_NMR_shifts_and_HSQC: [[199.3], [129.5, 6.01], [154.8, 6.82], [42.0], [33.9, 3.66, 3.66], [40.3, 1.86, 1.86], [152.8], [83.2], [28.2, 1.51, 1.51, 1.51], [28.2, 1.51, 1.51, 1.51], [28.2, 1.51, 1.51, 1.51], [152.8], [83.2], [28.2, 1.51, 1.51, 1.51], [28.2, 1.51, 1.51, 1.51], [28.2, 1.51, 1.51, 1.51], [28.4, 1.86, 1.86], [33.1, 2.47, 2.47], [66.8, 3.56, 3.66]]
  HH_COSY: [[129.5, 154.8], [33.9, 40.3], [28.4, 33.1]]
  num_OH: 1
  num_NH2: 0
  num_NH: 0
  #multi_molecules_input_files: 'inputs/example_input.csv' # Path to the batched molecular input file
                                                          # if not None, will overwrite the single molecular input
  multi_molecules_input_files: None
dataset:
  name: 'pcqm4mv2nmr-advanced-prediction-pa6-exp'
  edge_types: [8.4975e-01, 9.7150e-02, 8.6272e-03, 8.9793e-04, 4.2763e-02, 8.0763e-04]
train:
  batch_size: 256
  infer_start_id: 0
  multi_infer: 256
  visualize_chain: False
general:
  name: 'pcqm4mv2nmr-advanced-prediction-pa6-exp'
  gpus: [2]
  test_only: /home/hcchen/Di-GT-NMR-0317/src/Pretrained/pcqm4mv2nmr-advanced-best/checkpoints/pcqm4mv2nmr-advanced/epoch=1173.ckpt
  chains_to_save: 50
  log_every_steps: 1
  number_chain_steps: 50
model: # NOT NEED TO CHANGE
  type: 'discrete'
  transition: 'marginal'
  model: Di-GT-NMR
  diffusion_steps: 500
  diffusion_noise_schedule: custom
  n_layers: 20
  extra_features: all
  hidden_mlp_dims:
    X: 1024
    E: 512
    y: 512
  hidden_dims:
    dx: 1024
    de: 256
    dy: 256
    n_head: 32
    dim_ffX: 1024
    dim_ffE: 512
    dim_ffy: 512
  lambda_train:
  - 5
  - 0