# @package _global_
prediction_input:
  molecular_formula: 'C24H35NO6' # single molecular run
  C_H_NMR_shifts_and_HSQC: [[3.6, 1.72, 1.72, 1.72], [76.6], [77.6], [13.6, 2.45, 2.45], [38.8, 2.75, 2.75], [207.5], [52.4], [34.8, 2.0, 2.0], [42.1, 3.53, 3.53], [152.4], [83.0], [28.3, 1.5, 1.5, 1.5], [28.3, 1.5, 1.5, 1.5], [28.3, 1.5, 1.5, 1.5], [152.4], [83.0], [28.3, 1.5, 1.5, 1.5], [28.3, 1.5, 1.5, 1.5], [28.3, 1.5, 1.5, 1.5], [150.1, 7.01], [130.6, 6.09], [29.8, 2.0, 2.45], [36.5, 2.45, 2.45], [198.3]]
  HH_COSY: [[13.6, 38.8], [34.8, 42.1], [150.1, 130.6], [29.8, 36.5]]
  num_OH: 0
  num_NH2: 0
  num_NH: 0
  #multi_molecules_input_files: 'inputs/example_input.csv' # Path to the batched molecular input file
                                                          # if not None, will overwrite the single molecular input
  multi_molecules_input_files: None
dataset:
  name: 'pcqm4mv2nmr-advanced-prediction-pa7-exp'
  edge_types: [8.4975e-01, 9.7150e-02, 8.6272e-03, 8.9793e-04, 4.2763e-02, 8.0763e-04]
train:
  batch_size: 256
  infer_start_id: 0
  multi_infer: 256
  visualize_chain: False
general:
  name: 'pcqm4mv2nmr-advanced-prediction-pa7-exp'
  gpus: [3]
  test_only: /home/hcchen/Di-GT-NMR-0317/src/Pretrained/pcqm4mv2nmr-advanced-best/checkpoints/pcqm4mv2nmr-advanced/epoch=1173.ckpt
  chains_to_save: 50
  log_every_steps: 1
  number_chain_steps: 50
model: # NOT NEED TO CHANGE
  type: 'discrete'
  transition: 'marginal'
  model: Di-GT-NMR
  diffusion_steps: 500
  diffusion_noise_schedule: custom
  n_layers: 20
  extra_features: all
  hidden_mlp_dims:
    X: 1024
    E: 512
    y: 512
  hidden_dims:
    dx: 1024
    de: 256
    dy: 256
    n_head: 32
    dim_ffX: 1024
    dim_ffE: 512
    dim_ffy: 512
  lambda_train:
  - 5
  - 0