# @package _global_
prediction_input:
  molecular_formula: 'C23H29NO5' # single molecular run
  C_H_NMR_shifts_and_HSQC: [[58.4, 4.08, 3.83], [28.8, 2.12, 2.33], [55.1], [182.9], [201.4], [53.2, 3.78, 3.43], [107.2], [38.5, 2.33, 2.5], [24.6, 1.97, 1.97], [85.0, 4.15], [34.7, 1.87], [34.3, 1.58, 1.69], [79.1, 4.28], [204.8], [72.4, 4.62], [41.2, 2.79], [126.9, 5.11], [135.8], [22.8, 2.33, 2.33], [28.8, 1.78, 1.78], [138.8, 6.21], [112.5, 4.97, 5.07], [18.0, 0.91, 0.91, 0.91]]
  HH_COSY: [[58.4, 28.8], [38.5, 24.6], [24.6, 85.0], [85.0, 34.7], [34.7, 34.3], [34.7, 18.0], [34.3, 79.1], [41.2, 72.4], [126.9, 41.2], [28.8, 22.8], [112.5, 138.8]]
  num_OH: 1
  num_NH2: 0
  num_NH: 0
  #multi_molecules_input_files: 'inputs/example_input.csv' # Path to the batched molecular input file
                                                          # if not None, will overwrite the single molecular input
  multi_molecules_input_files: None
dataset:
  name: 'pcqm4mv2nmr-advanced-prediction-pb-exp'
  edge_types: [8.4975e-01, 9.7150e-02, 8.6272e-03, 8.9793e-04, 4.2763e-02, 8.0763e-04]
train:
  batch_size: 256
  infer_start_id: 0
  multi_infer: 256
  visualize_chain: False
general:
  name: 'pcqm4mv2nmr-advanced-prediction-pb-exp'
  gpus: [3]
  test_only: /home/hcchen/Di-GT-NMR-0317/src/Pretrained/pcqm4mv2nmr-advanced-best/checkpoints/pcqm4mv2nmr-advanced/epoch=1173.ckpt
  chains_to_save: 50
  log_every_steps: 1
  number_chain_steps: 50
model: # NOT NEED TO CHANGE
  type: 'discrete'
  transition: 'marginal'
  model: Di-GT-NMR
  diffusion_steps: 500
  diffusion_noise_schedule: custom
  n_layers: 20
  extra_features: all
  hidden_mlp_dims:
    X: 1024
    E: 512
    y: 512
  hidden_dims:
    dx: 1024
    de: 256
    dy: 256
    n_head: 32
    dim_ffX: 1024
    dim_ffE: 512
    dim_ffy: 512
  lambda_train:
  - 5
  - 0