# @package _global_
prediction_input:
  molecular_formula: 'C17H26O3' # single molecular run
  C_H_NMR_shifts_and_HSQC: [[26.9,1.01,1.76],[22.3,1.27,1.47],[28.9,1.27,1.27],[36.6,1.28],[45.5],[46.0,2.15],[71.5,5.26],[23.9,1.37,2.05],[29.7,1.28,1.58],[54.7],[41.5,2.38],[222.6],[18.9, 1.32, 1.32, 1.32],[15.3, 0.84, 0.84, 0.84],[10.4,0.98,0.98,0.98],[170.7],[21.3,2.03,2.03,2.03]]
  HH_COSY: [[26.9,22.3],[22.3,28.9],[28.9,36.6],[36.6,15.3],[46.0,71.5],[46.0,41.5],[41.5,18.9],[71.5,23.9],[23.9,29.7]]
  num_OH: 0
  num_NH2: 0
  num_NH: 0
  #multi_molecules_input_files: 'inputs/example_input.csv' # Path to the batched molecular input file
                                                          # if not None, will overwrite the single molecular input
  multi_molecules_input_files: None
dataset:
  name: 'pcqm4mv2nmr-advanced-prediction-bellissinanes-1-1173-exp'
  edge_types: [8.4975e-01, 9.7150e-02, 8.6272e-03, 8.9793e-04, 4.2763e-02, 8.0763e-04]
train:
  batch_size: 256
  infer_start_id: 0
  multi_infer: 256
  visualize_chain: False
general:
  name: 'pcqm4mv2nmr-advanced-prediction-bellissinanes-1-1173-exp'
  gpus: [0]
  test_only: /home/hcchen/Di-GT-NMR-0317/src/Pretrained/pcqm4mv2nmr-advanced-best/checkpoints/pcqm4mv2nmr-advanced/epoch=1173.ckpt
  chains_to_save: 50
  log_every_steps: 1
  number_chain_steps: 50
model: # NOT NEED TO CHANGE
  type: 'discrete'
  transition: 'marginal'
  model: Di-GT-NMR
  diffusion_steps: 500
  diffusion_noise_schedule: custom
  n_layers: 20
  extra_features: all
  hidden_mlp_dims:
    X: 1024
    E: 512
    y: 512
  hidden_dims:
    dx: 1024
    de: 256
    dy: 256
    n_head: 32
    dim_ffX: 1024
    dim_ffE: 512
    dim_ffy: 512
  lambda_train:
  - 5
  - 0