# @package _global_
prediction_input:
  molecular_formula: 'C14H24O4' # single molecular run
  C_H_NMR_shifts_and_HSQC: [[72.7, 3.48], [30.3, 1.58, 1.91], [29.8, 1.38, 1.38], [32.1, 1.9], [46.6], [64.1, 3.47], [69.3, 4.2], [26.9, 1.69, 1.69], [30.4, 1.83, 1.6], [74.0], [218.9], [36.0, 2.45, 2.45, 2.45], [16.0, 0.77, 0.77, 0.77], [17.7, 0.98, 0.98, 0.98]]
  HH_COSY: [[64.1, 69.3], [69.3, 26.9], [26.9, 30.4], [32.1, 17.7], [32.1, 30.3], [30.3, 29.8], [29.8, 72.7]]
  num_OH: 3
  num_NH2: 0
  num_NH: 0
  #multi_molecules_input_files: 'inputs/example_input.csv' # Path to the batched molecular input file
                                                          # if not None, will overwrite the single molecular input
  multi_molecules_input_files: None
dataset:
  name: 'pcqm4mv2nmr-advanced-prediction-bellissinanes-7-639-exp'
  edge_types: [8.4975e-01, 9.7150e-02, 8.6272e-03, 8.9793e-04, 4.2763e-02, 8.0763e-04]
train:
  batch_size: 256
  infer_start_id: 0
  multi_infer: 256
  visualize_chain: False
general:
  name: 'pcqm4mv2nmr-advanced-prediction-bellissinanes-7-639-exp'
  gpus: [1]
  test_only: /home/hcchen/Di-GT-NMR-0317/src/Pretrained/pcqm4mv2nmr-advanced-best/checkpoints/pcqm4mv2nmr-advanced/epoch=639.ckpt
  chains_to_save: 50
  log_every_steps: 1
  number_chain_steps: 50
model: # NOT NEED TO CHANGE
  type: 'discrete'
  transition: 'marginal'
  model: Di-GT-NMR
  diffusion_steps: 500
  diffusion_noise_schedule: custom
  n_layers: 20
  extra_features: all
  hidden_mlp_dims:
    X: 1024
    E: 512
    y: 512
  hidden_dims:
    dx: 1024
    de: 256
    dy: 256
    n_head: 32
    dim_ffX: 1024
    dim_ffE: 512
    dim_ffy: 512
  lambda_train:
  - 5
  - 0